// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXAM_7iRZZmLpiCYn1PGrR_bPbaq_kPQ8',
    appId: '1:398354109407:web:25babe01668271e361aa6a',
    messagingSenderId: '398354109407',
    projectId: 'dealer-management-b84ae',
    authDomain: 'dealer-management-b84ae.firebaseapp.com',
    storageBucket: 'dealer-management-b84ae.firebasestorage.app',
    measurementId: 'G-0224F7SPCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFOuWm45Z8pz9Dyem9f5ABbgesJ-4oosA',
    appId: '1:398354109407:android:ecb093a72abdd7f861aa6a',
    messagingSenderId: '398354109407',
    projectId: 'dealer-management-b84ae',
    storageBucket: 'dealer-management-b84ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2aj9tTbMO8NLPrpkRyKFV6y0TFZ6YPf8',
    appId: '1:398354109407:ios:870bc9c543f1eed961aa6a',
    messagingSenderId: '398354109407',
    projectId: 'dealer-management-b84ae',
    storageBucket: 'dealer-management-b84ae.firebasestorage.app',
    iosClientId: '398354109407-7j2g7q25rl636uj3s9c3l2f7fut7hh24.apps.googleusercontent.com',
    iosBundleId: 'com.example.dealer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2aj9tTbMO8NLPrpkRyKFV6y0TFZ6YPf8',
    appId: '1:398354109407:ios:870bc9c543f1eed961aa6a',
    messagingSenderId: '398354109407',
    projectId: 'dealer-management-b84ae',
    storageBucket: 'dealer-management-b84ae.firebasestorage.app',
    iosClientId: '398354109407-7j2g7q25rl636uj3s9c3l2f7fut7hh24.apps.googleusercontent.com',
    iosBundleId: 'com.example.dealer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXAM_7iRZZmLpiCYn1PGrR_bPbaq_kPQ8',
    appId: '1:398354109407:web:768d5707fc70e54b61aa6a',
    messagingSenderId: '398354109407',
    projectId: 'dealer-management-b84ae',
    authDomain: 'dealer-management-b84ae.firebaseapp.com',
    storageBucket: 'dealer-management-b84ae.firebasestorage.app',
    measurementId: 'G-MY9S890STE',
  );
}
